Add lists
tmampa/to-do-list pull request #1
Opened 2021-09-15 11:11 UTC by tmampa

# To-do List App

## Built using Javascript

## - Users can
- Add tasks
- Change dates
- Delete tasks
- Edit tasks
- Add projects

2021-09-15 12:51 UTC, mke2111 requested changes
### Hey , 

**This is a great project you have going on, well-done lad**. 
   
**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

## Required Changes ♻️
_Check the inline comments under the review for sections to improve._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2021-09-15 12:54 UTC, mke2111 commented on src/modules/Task.js
> +}
- [ ] Each task should at least contain a title, description, due date, and priority. Your task is missing the description and priority fields.

2021-09-15 12:57 UTC, mke2111 commented on package.json
> +    "webpack-cli": "^4.8.0"
- [ ] Add `webpack-dev-server` to your devDependencies.

2021-09-15 12:58 UTC, mke2111 commented on package.json
> +  },
- [ ] Add all the necessary run commands to your scripts.
```
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
```

2021-09-15 13:27 UTC, mke2111 requested changes
### Hey @tmampa, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2021-09-15 13:29 UTC, mke2111 commented on src/modules/Task.js
> +
- [ ] As previously requested, add these fields to the task.
> Each task should at least contain a title, description, due date, and priority. Your task is missing the description and priority fields.

2021-09-17 11:51 UTC, george-shammar approved these changes
Hi @tmampa , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-17 19:52 UTC, merged